name: Build Light APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Strip Debug Overhead Safely
        run: |
          sed -i '/debug {/A \
              debuggable false\n\
              jniDebuggable false\n\
              renderscriptDebuggable false\n\
          ' app/build.gradle || true

      - name: Build Lightweight APK
        run: ./gradlew assembleDebug

      - name: Upload Cleaned APK File
        uses: actions/upload-artifact@v4
        with:
          name: Droidcord-Light-APK
          path: app/build/outputs/apk/debug/app-debug.apk
